-- Day-of-week surcharges, e.g. weekends cost more. Applied on top of the show's category price.
CREATE TABLE pricing_rule (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(80)  NOT NULL,
    scope_type        VARCHAR(10)  NOT NULL CHECK (scope_type IN ('GLOBAL', 'CITY', 'THEATER')),
    scope_id          BIGINT,                                 -- city or theater id; NULL for GLOBAL
    days_of_week      SMALLINT[]   NOT NULL,                  -- ISO: 1 = Monday ... 7 = Sunday
    adjustment_type   VARCHAR(10)  NOT NULL CHECK (adjustment_type IN ('PERCENT', 'FLAT')),
    adjustment_value  BIGINT       NOT NULL CHECK (adjustment_value > 0),   -- percent (20) or paise per seat
    valid_from        DATE,
    valid_to          DATE,
    active            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        UUID,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by        UUID,
    CHECK ((scope_type = 'GLOBAL') = (scope_id IS NULL)),
    CHECK (cardinality(days_of_week) > 0 AND days_of_week <@ ARRAY[1, 2, 3, 4, 5, 6, 7]::SMALLINT[]),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

INSERT INTO pricing_rule (name, scope_type, days_of_week, adjustment_type, adjustment_value)
VALUES ('Weekend +20%', 'GLOBAL', '{6,7}', 'PERCENT', 20);
