CREATE TABLE coupon (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(30)  NOT NULL UNIQUE,              -- stored upper-case
    discount_type       VARCHAR(10)  NOT NULL CHECK (discount_type IN ('FLAT', 'PERCENT')),
    discount_value      BIGINT       NOT NULL CHECK (discount_value > 0),   -- paise, or percent
    max_discount_paise  BIGINT       CHECK (max_discount_paise > 0),        -- cap for PERCENT coupons
    min_order_paise     BIGINT       NOT NULL DEFAULT 0 CHECK (min_order_paise >= 0),
    valid_from          TIMESTAMPTZ  NOT NULL,
    valid_to            TIMESTAMPTZ  NOT NULL,
    max_uses            INT          CHECK (max_uses > 0),        -- NULL = unlimited
    used_count          INT          NOT NULL DEFAULT 0,          -- reserved + consumed; only changed by redemption SQL
    per_user_limit      INT          NOT NULL DEFAULT 1 CHECK (per_user_limit > 0),
    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          UUID,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by          UUID,
    CHECK (valid_to > valid_from),
    CHECK (discount_type = 'FLAT' OR discount_value <= 100),
    CHECK (discount_type = 'PERCENT' OR max_discount_paise IS NULL),
    CHECK (used_count >= 0 AND (max_uses IS NULL OR used_count <= max_uses))
);

-- No rows: the coupon works everywhere. Rows of the same type are OR-ed, different types are AND-ed.
CREATE TABLE coupon_scope (
    coupon_id   BIGINT       NOT NULL REFERENCES coupon(id),
    scope_type  VARCHAR(10)  NOT NULL CHECK (scope_type IN ('CITY', 'THEATER', 'MOVIE', 'CATEGORY')),
    scope_id    BIGINT       NOT NULL,
    PRIMARY KEY (coupon_id, scope_type, scope_id)
);
