-- How often each customer has used each coupon (reserved + consumed), for the per-user limit.
CREATE TABLE coupon_user_usage (
    coupon_id   BIGINT  NOT NULL REFERENCES coupon(id),
    user_id     UUID    NOT NULL,
    used_count  INT     NOT NULL CHECK (used_count >= 0),
    PRIMARY KEY (coupon_id, user_id)
);

-- A coupon on a booking. RESERVED while held, CONSUMED once paid, RELEASED when given back.
-- No foreign key to booking: the coupon is reserved before the booking row is inserted, in the same transaction.
CREATE TABLE coupon_redemption (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id       BIGINT       NOT NULL REFERENCES coupon(id),
    user_id         UUID         NOT NULL,
    booking_id      UUID         NOT NULL,
    discount_paise  BIGINT       NOT NULL CHECK (discount_paise >= 0),
    status          VARCHAR(10)  NOT NULL CHECK (status IN ('RESERVED', 'CONSUMED', 'RELEASED')),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX coupon_redemption_one_live ON coupon_redemption (booking_id) WHERE status <> 'RELEASED';

ALTER TABLE booking ADD COLUMN coupon_code VARCHAR(30);
