-- Who the gateway says each caller is, kept so notifications can reach them later
CREATE TABLE app_user (
    id          UUID         PRIMARY KEY,                -- from X-User-Id
    name        VARCHAR(120),
    email       VARCHAR(254),
    phone       VARCHAR(20),
    role        VARCHAR(10)  NOT NULL CHECK (role IN ('ADMIN', 'CUSTOMER')),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE notification_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    UUID         NOT NULL,
    type          VARCHAR(20)  NOT NULL CHECK (type IN
                    ('BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REFUND_COMPLETED', 'SHOW_REMINDER')),
    reference_id  VARCHAR(64)  NOT NULL DEFAULT '',      -- cancellation or refund id; '' when a type happens once
    channel       VARCHAR(8)   NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    status        VARCHAR(8)   NOT NULL CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    attempts      INT          NOT NULL DEFAULT 0,
    last_error    VARCHAR(300),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    sent_at       TIMESTAMPTZ
);
-- one message per booking, type, reference and channel, however often the event is delivered
CREATE UNIQUE INDEX notification_dedupe ON notification_log (booking_id, type, reference_id, channel);
