CREATE TABLE refund_policy (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(80)  NOT NULL UNIQUE,
    type         VARCHAR(16)  NOT NULL CHECK (type IN ('SLAB', 'FULL', 'NON_REFUNDABLE')),
    refund_fees  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(), created_by UUID,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(), updated_by UUID
);
CREATE UNIQUE INDEX refund_policy_one_default ON refund_policy (is_default) WHERE is_default;

-- "cancel at least min_hours_before the show and get refund_percent of the ticket price back"
CREATE TABLE refund_policy_slab (
    policy_id         BIGINT NOT NULL REFERENCES refund_policy(id),
    min_hours_before  INT    NOT NULL CHECK (min_hours_before >= 0),
    refund_percent    INT    NOT NULL CHECK (refund_percent BETWEEN 0 AND 100),
    PRIMARY KEY (policy_id, min_hours_before)
);

-- a show without a policy uses the default one
ALTER TABLE show ADD COLUMN refund_policy_id BIGINT REFERENCES refund_policy(id);

-- the policy as it was when the booking was confirmed; later edits to the policy don't change it
ALTER TABLE booking ADD COLUMN refund_policy_snapshot JSONB;

-- there must always be a default, so confirmation always has a policy to snapshot
INSERT INTO refund_policy (name, type, refund_fees, is_default) VALUES ('Standard', 'SLAB', FALSE, TRUE);
INSERT INTO refund_policy_slab (policy_id, min_hours_before, refund_percent)
SELECT id, slab.hours, slab.percent
FROM refund_policy, (VALUES (24, 100), (4, 50), (0, 0)) AS slab (hours, percent)
WHERE name = 'Standard';
