CREATE TABLE theater (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id     BIGINT       NOT NULL REFERENCES city(id),
    name        VARCHAR(120) NOT NULL,
    area        VARCHAR(120),
    address     VARCHAR(300),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  UUID,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  UUID,
    UNIQUE (city_id, name)
);

CREATE TABLE screen (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id  BIGINT       NOT NULL REFERENCES theater(id),
    name        VARCHAR(40)  NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  UUID,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  UUID,
    UNIQUE (theater_id, name)
);
