CREATE TABLE movie (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(200) NOT NULL,
    duration_min   INT          NOT NULL CHECK (duration_min > 0),
    certification  VARCHAR(10)  NOT NULL CHECK (certification IN ('U', 'UA', 'A', 'S')),
    release_date   DATE,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     UUID,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by     UUID
);
