CREATE TABLE seat_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(40)  NOT NULL,
    sort_order  INT          NOT NULL
);

INSERT INTO seat_category (code, name, sort_order) VALUES
    ('REGULAR',  'Regular',  1),
    ('PREMIUM',  'Premium',  2),
    ('RECLINER', 'Recliner', 3);

CREATE TABLE seat_layout (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id    BIGINT       NOT NULL REFERENCES screen(id),
    version      INT          NOT NULL,
    status       VARCHAR(10)  NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    grid_rows    INT          NOT NULL CHECK (grid_rows > 0),
    grid_cols    INT          NOT NULL CHECK (grid_cols > 0),
    total_seats  INT          NOT NULL CHECK (total_seats > 0),   -- sellable seats, i.e. not blocked
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   UUID,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by   UUID,
    UNIQUE (screen_id, version)
);
CREATE UNIQUE INDEX seat_layout_one_active ON seat_layout (screen_id) WHERE status = 'ACTIVE';

CREATE TABLE layout_seat (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layout_id    BIGINT       NOT NULL REFERENCES seat_layout(id),
    row_label    VARCHAR(4)   NOT NULL,
    seat_number  INT          NOT NULL,
    grid_row     INT          NOT NULL,
    grid_col     INT          NOT NULL,
    category_id  BIGINT       NOT NULL REFERENCES seat_category(id),
    seat_type    VARCHAR(12)  NOT NULL CHECK (seat_type IN ('NORMAL', 'WHEELCHAIR', 'BLOCKED')),
    UNIQUE (layout_id, row_label, seat_number),
    UNIQUE (layout_id, grid_row, grid_col)
);
