CREATE EXTENSION IF NOT EXISTS btree_gist;   -- lets the exclusion constraint combine = on screen_id with && on ranges

CREATE TABLE show (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id       BIGINT       NOT NULL REFERENCES movie(id),
    screen_id      BIGINT       NOT NULL REFERENCES screen(id),
    theater_id     BIGINT       NOT NULL REFERENCES theater(id),   -- copied from the screen, for search
    city_id        BIGINT       NOT NULL REFERENCES city(id),      -- copied from the theater, for search
    layout_id      BIGINT       NOT NULL REFERENCES seat_layout(id),
    show_date      DATE         NOT NULL,                          -- listing date (late-night shows go under the day before)
    start_time     TIMESTAMPTZ  NOT NULL,
    end_time       TIMESTAMPTZ  NOT NULL,
    blocked_until  TIMESTAMPTZ  NOT NULL,                          -- end_time + cleaning buffer
    language       VARCHAR(10)  NOT NULL,
    format         VARCHAR(10)  NOT NULL,
    status         VARCHAR(10)  NOT NULL CHECK (status IN ('SCHEDULED', 'OPEN', 'CANCELLED')),
    total_seats    INT          NOT NULL CHECK (total_seats > 0),
    version        BIGINT       NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     UUID,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by     UUID,
    CHECK (end_time > start_time AND blocked_until >= end_time),
    CONSTRAINT show_no_overlap EXCLUDE USING gist (
        screen_id WITH =,
        tstzrange(start_time, blocked_until) WITH &&
    ) WHERE (status <> 'CANCELLED')
);
CREATE INDEX show_browse_idx  ON show (city_id, movie_id, show_date, start_time);
CREATE INDEX show_theater_idx ON show (theater_id, show_date);
